# Generated by Django 4.1.3 on 2022-11-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyArtikel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Judul", models.CharField(max_length=200)),
                ("isiArtikel", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("gambar", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "MyArtikel",
            },
        ),
    ]
