# Generated by Django 4.1.3 on 2022-12-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_weathercek"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weathercek",
            name="temp",
            field=models.IntegerField(blank=True, max_length=225, null=True),
        ),
    ]
