# Generated by Django 4.1.3 on 2022-12-21 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_weathercek_cuaca"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weathercek",
            options={"verbose_name_plural": "MyWeather"},
        ),
    ]
